apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: kafka-test-apps
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 3
  config:
      retention.bytes: 1073741824
      retention.ms: 86400000
      segment.bytes: 1073741824
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-producer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kafka-producer
rules:
  - apiGroups:
      - "kafka.strimzi.io"
    resources:
      - kafkatopics
    verbs:
      - list
      - update
    resourceNames:
      - kafka-test-apps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kafka-producer
subjects:
  - kind: ServiceAccount
    name: kafka-producer
roleRef:
  kind: Role
  name: kafka-producer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kafka-producer
  name: kafka-producer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      serviceAccountName: kafka-producer
      containers:
      - name: kafka-producer
        image: scholzj/kafka-producer:latest
        env:
          - name: BOOTSTRAP_SERVERS
            value: my-cluster-kafka-bootstrap:9092
          - name: TOPIC
            value: kafka-test-apps
          - name: TIMER
            value: "1000"
          - name: NUMBER_OF_KEYS
            value: "3"
          - name: AUTH
            value: "kubernetes"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-consumer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kafka-consumer
rules:
  - apiGroups:
      - "kafka.strimzi.io"
    resources:
      - kafkatopics
    verbs:
      - list
      - get
    resourceNames:
      - kafka-test-apps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kafka-consumer
subjects:
  - kind: ServiceAccount
    name: kafka-consumer
roleRef:
  kind: Role
  name: kafka-consumer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kafka-consumer
  name: kafka-consumer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      serviceAccountName: kafka-consumer
      containers:
      - name: kafka-consumer
        image: scholzj/kafka-consumer:latest
        env:
          - name: BOOTSTRAP_SERVERS
            value: my-cluster-kafka-bootstrap:9092
          - name: TOPIC
            value: kafka-test-apps
          - name: GROUP_ID
            value: "system:serviceaccount:myproject:kafka-consumer"
          - name: AUTH
            value: "kubernetes"
