apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: unauthorized-kafka-producer
  name: unauthorized-kafka-producer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: unauthorized-kafka-producer
    spec:
      containers:
      - name: unauthorized-kafka-producer
        image: scholzj/kafka-producer:latest
        env:
          - name: BOOTSTRAP_SERVERS
            value: my-cluster-kafka-bootstrap:9092
          - name: TOPIC
            value: kafka-test-apps
          - name: TIMER
            value: "1000"
          - name: NUMBER_OF_KEYS
            value: "3"
          - name: AUTH
            value: "kubernetes"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: unauthenticated-kafka-consumer
  name: unauthenticated-kafka-consumer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: unauthenticated-kafka-consumer
    spec:
      containers:
      - name: kafka-consumer
        image: scholzj/kafka-consumer:latest
        env:
          - name: BOOTSTRAP_SERVERS
            value: my-cluster-kafka-bootstrap:9092
          - name: TOPIC
            value: kafka-test-apps
          - name: GROUP_ID
            value: "system:serviceaccount:myproject:kafka-consumer"
          - name: AUTH
            value: "kubernetes"
          - name: TOKEN
            value: eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJteXByb2plY3QiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoic3RyaW16aS1jbHVzdGVyLW9wZXJhdG9yLXRva2VuLXE5Z2Q4Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InN0cmltemktY2x1c3Rlci1vcGVyYXRvciIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjI4YmQxN2U3LWE3ZjctMTFlOS05YzA2LTMyMWYxYWMxZjU5ZCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpteXByb2plY3Q6c3RyaW16aS1jbHVzdGVyLW9wZXJhdG9yIn0.VUut5rtG4tAheJj33LiK5qhd4dFaS7E9bXGbkn2Hf5I2p3qyc-C5ise1fy37mgTo1wW9cP188UQb-rqn7MEbR3rELMbBP42UgI5eE8kybr-MUvyDABElqEXlvuLt_yPLNOlZEhvv2X4b_Y9papj7dx4YKO-MEeHzfKnhdV4R2PUwEtU6RyvfXDkDrTTRlhdEzlVo_5vdemyaEvw4Epfu0yGKH4ZQAgRkTfuB0d08o9HvUcsRLCJxdFM6eaqepN2gfo5DK2rZNgoDBWl-ny5-ZoqKlY4x-5rN52e3Av_VgRGMrLA-SbVq7u6s6n_0g0ILFQREsfdJaJuvWf8mFQ_h9A
